[2024-12-27T03:43:51.265+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-27T03:43:51.285+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prediction_dag_v1.predict_model manual__2024-12-27T03:43:43.143920+00:00 [queued]>
[2024-12-27T03:43:51.295+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prediction_dag_v1.predict_model manual__2024-12-27T03:43:43.143920+00:00 [queued]>
[2024-12-27T03:43:51.295+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-27T03:43:51.309+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): predict_model> on 2024-12-27 03:43:43.143920+00:00
[2024-12-27T03:43:51.317+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=221) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-27T03:43:51.319+0000] {standard_task_runner.py:72} INFO - Started process 223 to run task
[2024-12-27T03:43:51.319+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'prediction_dag_v1', 'predict_model', 'manual__2024-12-27T03:43:43.143920+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/02_prediction/02_prediction_v1.py', '--cfg-path', '/tmp/tmpdckwsx7u']
[2024-12-27T03:43:51.320+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask predict_model
[2024-12-27T03:43:51.374+0000] {task_command.py:467} INFO - Running <TaskInstance: prediction_dag_v1.predict_model manual__2024-12-27T03:43:43.143920+00:00 [running]> on host f83652127260
[2024-12-27T03:43:51.965+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cm' AIRFLOW_CTX_DAG_ID='prediction_dag_v1' AIRFLOW_CTX_TASK_ID='predict_model' AIRFLOW_CTX_EXECUTION_DATE='2024-12-27T03:43:43.143920+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-27T03:43:43.143920+00:00'
[2024-12-27T03:43:51.967+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-27T03:43:51.969+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-27T03:43:51.970+0000] {logging_mixin.py:190} INFO - Current task name:predict_model state:running start_date:2024-12-27 03:43:51.286279+00:00
[2024-12-27T03:43:51.972+0000] {logging_mixin.py:190} INFO - Dag name:prediction_dag_v1 and current dag run status:running
[2024-12-27T03:43:51.974+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-27T03:43:51.976+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvl7wxwrs6 --python=python
[2024-12-27T03:43:51.978+0000] {process_utils.py:190} INFO - Output:
[2024-12-27T03:43:53.365+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.7.final.0-64 in 434ms
[2024-12-27T03:43:53.367+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venvl7wxwrs6, clear=False, no_vcs_ignore=False, global=False)
[2024-12-27T03:43:53.367+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-12-27T03:43:53.370+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2024-12-27T03:43:53.372+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-12-27T03:43:53.423+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvl7wxwrs6/bin/pip install -r /tmp/venvl7wxwrs6/requirements.txt
[2024-12-27T03:43:53.427+0000] {process_utils.py:190} INFO - Output:
[2024-12-27T03:43:55.095+0000] {process_utils.py:194} INFO - Collecting feature-engine==1.8.2 (from -r /tmp/venvl7wxwrs6/requirements.txt (line 1))
[2024-12-27T03:43:55.101+0000] {process_utils.py:194} INFO -   Using cached feature_engine-1.8.2-py2.py3-none-any.whl.metadata (9.9 kB)
[2024-12-27T03:43:55.156+0000] {process_utils.py:194} INFO - Collecting joblib==1.3.2 (from -r /tmp/venvl7wxwrs6/requirements.txt (line 2))
[2024-12-27T03:43:55.158+0000] {process_utils.py:194} INFO -   Using cached joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
[2024-12-27T03:43:55.386+0000] {process_utils.py:194} INFO - Collecting numpy==1.26.4 (from -r /tmp/venvl7wxwrs6/requirements.txt (line 3))
[2024-12-27T03:43:55.388+0000] {process_utils.py:194} INFO -   Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
[2024-12-27T03:43:55.756+0000] {process_utils.py:194} INFO - Collecting pandas==2.2.3 (from -r /tmp/venvl7wxwrs6/requirements.txt (line 4))
[2024-12-27T03:43:55.758+0000] {process_utils.py:194} INFO -   Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
[2024-12-27T03:43:55.969+0000] {process_utils.py:194} INFO - Collecting scikit-learn==1.5.2 (from -r /tmp/venvl7wxwrs6/requirements.txt (line 5))
[2024-12-27T03:43:55.973+0000] {process_utils.py:194} INFO -   Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
[2024-12-27T03:43:56.159+0000] {process_utils.py:194} INFO - Collecting scipy>=1.4.1 (from feature-engine==1.8.2->-r /tmp/venvl7wxwrs6/requirements.txt (line 1))
[2024-12-27T03:43:56.162+0000] {process_utils.py:194} INFO -   Using cached scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
[2024-12-27T03:43:56.260+0000] {process_utils.py:194} INFO - Collecting statsmodels>=0.11.1 (from feature-engine==1.8.2->-r /tmp/venvl7wxwrs6/requirements.txt (line 1))
[2024-12-27T03:43:56.262+0000] {process_utils.py:194} INFO -   Using cached statsmodels-0.14.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.2 kB)
[2024-12-27T03:43:56.305+0000] {process_utils.py:194} INFO - Collecting python-dateutil>=2.8.2 (from pandas==2.2.3->-r /tmp/venvl7wxwrs6/requirements.txt (line 4))
[2024-12-27T03:43:56.307+0000] {process_utils.py:194} INFO -   Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
[2024-12-27T03:43:56.378+0000] {process_utils.py:194} INFO - Collecting pytz>=2020.1 (from pandas==2.2.3->-r /tmp/venvl7wxwrs6/requirements.txt (line 4))
[2024-12-27T03:43:56.380+0000] {process_utils.py:194} INFO -   Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
[2024-12-27T03:43:56.420+0000] {process_utils.py:194} INFO - Collecting tzdata>=2022.7 (from pandas==2.2.3->-r /tmp/venvl7wxwrs6/requirements.txt (line 4))
[2024-12-27T03:43:56.422+0000] {process_utils.py:194} INFO -   Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
[2024-12-27T03:43:56.469+0000] {process_utils.py:194} INFO - Collecting threadpoolctl>=3.1.0 (from scikit-learn==1.5.2->-r /tmp/venvl7wxwrs6/requirements.txt (line 5))
[2024-12-27T03:43:56.472+0000] {process_utils.py:194} INFO -   Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
[2024-12-27T03:43:56.524+0000] {process_utils.py:194} INFO - Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas==2.2.3->-r /tmp/venvl7wxwrs6/requirements.txt (line 4))
[2024-12-27T03:43:56.526+0000] {process_utils.py:194} INFO -   Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
[2024-12-27T03:43:56.598+0000] {process_utils.py:194} INFO - Collecting patsy>=0.5.6 (from statsmodels>=0.11.1->feature-engine==1.8.2->-r /tmp/venvl7wxwrs6/requirements.txt (line 1))
[2024-12-27T03:43:56.600+0000] {process_utils.py:194} INFO -   Using cached patsy-1.0.1-py2.py3-none-any.whl.metadata (3.3 kB)
[2024-12-27T03:43:56.651+0000] {process_utils.py:194} INFO - Collecting packaging>=21.3 (from statsmodels>=0.11.1->feature-engine==1.8.2->-r /tmp/venvl7wxwrs6/requirements.txt (line 1))
[2024-12-27T03:43:56.652+0000] {process_utils.py:194} INFO -   Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
[2024-12-27T03:43:56.667+0000] {process_utils.py:194} INFO - Using cached feature_engine-1.8.2-py2.py3-none-any.whl (374 kB)
[2024-12-27T03:43:56.669+0000] {process_utils.py:194} INFO - Using cached joblib-1.3.2-py3-none-any.whl (302 kB)
[2024-12-27T03:43:56.671+0000] {process_utils.py:194} INFO - Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
[2024-12-27T03:43:56.706+0000] {process_utils.py:194} INFO - Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
[2024-12-27T03:43:56.733+0000] {process_utils.py:194} INFO - Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
[2024-12-27T03:43:56.758+0000] {process_utils.py:194} INFO - Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
[2024-12-27T03:43:56.760+0000] {process_utils.py:194} INFO - Using cached pytz-2024.2-py2.py3-none-any.whl (508 kB)
[2024-12-27T03:43:56.763+0000] {process_utils.py:194} INFO - Using cached scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (40.8 MB)
[2024-12-27T03:43:56.865+0000] {process_utils.py:194} INFO - Using cached statsmodels-0.14.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.7 MB)
[2024-12-27T03:43:56.903+0000] {process_utils.py:194} INFO - Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
[2024-12-27T03:43:56.905+0000] {process_utils.py:194} INFO - Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)
[2024-12-27T03:43:56.907+0000] {process_utils.py:194} INFO - Using cached packaging-24.2-py3-none-any.whl (65 kB)
[2024-12-27T03:43:56.908+0000] {process_utils.py:194} INFO - Using cached patsy-1.0.1-py2.py3-none-any.whl (232 kB)
[2024-12-27T03:43:56.910+0000] {process_utils.py:194} INFO - Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
[2024-12-27T03:43:57.145+0000] {process_utils.py:194} INFO - Installing collected packages: pytz, tzdata, threadpoolctl, six, packaging, numpy, joblib, scipy, python-dateutil, patsy, scikit-learn, pandas, statsmodels, feature-engine
[2024-12-27T03:44:19.601+0000] {process_utils.py:194} INFO - Successfully installed feature-engine-1.8.2 joblib-1.3.2 numpy-1.26.4 packaging-24.2 pandas-2.2.3 patsy-1.0.1 python-dateutil-2.9.0.post0 pytz-2024.2 scikit-learn-1.5.2 scipy-1.14.1 six-1.17.0 statsmodels-0.14.4 threadpoolctl-3.5.0 tzdata-2024.2
[2024-12-27T03:44:20.141+0000] {python.py:513} INFO - Use 'pickle' as serializer.
[2024-12-27T03:44:20.174+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvl7wxwrs6/bin/python /tmp/venv-call4nfscw90/script.py /tmp/venv-call4nfscw90/script.in /tmp/venv-call4nfscw90/script.out /tmp/venv-call4nfscw90/string_args.txt /tmp/venv-call4nfscw90/termination.log
[2024-12-27T03:44:20.176+0000] {process_utils.py:190} INFO - Output:
[2024-12-27T03:44:22.289+0000] {process_utils.py:194} INFO - Traceback (most recent call last):
[2024-12-27T03:44:22.290+0000] {process_utils.py:194} INFO -   File "/tmp/venv-call4nfscw90/script.py", line 53, in <module>
[2024-12-27T03:44:22.291+0000] {process_utils.py:194} INFO -     res = task_predict_model(*arg_dict["args"], **arg_dict["kwargs"])
[2024-12-27T03:44:22.291+0000] {process_utils.py:194} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-27T03:44:22.292+0000] {process_utils.py:194} INFO -   File "/tmp/venv-call4nfscw90/script.py", line 30, in task_predict_model
[2024-12-27T03:44:22.293+0000] {process_utils.py:194} INFO -     predicciones = pipeline_de_produccion.predict(data)
[2024-12-27T03:44:22.293+0000] {process_utils.py:194} INFO -                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-27T03:44:22.294+0000] {process_utils.py:194} INFO -   File "/tmp/venvl7wxwrs6/lib/python3.12/site-packages/sklearn/pipeline.py", line 600, in predict
[2024-12-27T03:44:22.295+0000] {process_utils.py:194} INFO -     Xt = transform.transform(Xt)
[2024-12-27T03:44:22.296+0000] {process_utils.py:194} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-27T03:44:22.297+0000] {process_utils.py:194} INFO -   File "/tmp/venvl7wxwrs6/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 316, in wrapped
[2024-12-27T03:44:22.298+0000] {process_utils.py:194} INFO -     data_to_wrap = f(self, X, *args, **kwargs)
[2024-12-27T03:44:22.298+0000] {process_utils.py:194} INFO -                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-27T03:44:22.299+0000] {process_utils.py:194} INFO -   File "/tmp/venvl7wxwrs6/lib/python3.12/site-packages/feature_engine/transformation/yeojohnson.py", line 157, in transform
[2024-12-27T03:44:22.299+0000] {process_utils.py:194} INFO -     X = self._check_transform_input_and_state(X)
[2024-12-27T03:44:22.300+0000] {process_utils.py:194} INFO -         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-27T03:44:22.301+0000] {process_utils.py:194} INFO -   File "/tmp/venvl7wxwrs6/lib/python3.12/site-packages/feature_engine/_base_transformers/base_numerical.py", line 109, in _check_transform_input_and_state
[2024-12-27T03:44:22.302+0000] {process_utils.py:194} INFO -     _check_X_matches_training_df(X, self.n_features_in_)
[2024-12-27T03:44:22.303+0000] {process_utils.py:194} INFO -   File "/tmp/venvl7wxwrs6/lib/python3.12/site-packages/feature_engine/dataframe_checks.py", line 239, in _check_X_matches_training_df
[2024-12-27T03:44:22.304+0000] {process_utils.py:194} INFO -     raise ValueError(
[2024-12-27T03:44:22.304+0000] {process_utils.py:194} INFO - ValueError: The number of columns in this dataset is different from the one used to fit this transformer (when using the fit() method).
[2024-12-27T03:44:22.988+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 870, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 588, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
The number of columns in this dataset is different from the one used to fit this transformer (when using the fit() method).
[2024-12-27T03:44:23.004+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-27T03:44:23.005+0000] {logging_mixin.py:190} INFO - Task start:2024-12-27 03:43:51.286279+00:00 end:2024-12-27 03:44:23.003968+00:00 duration:31.717689
[2024-12-27T03:44:23.007+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonVirtualenvDecoratedOperator): predict_model> dag:<DAG: prediction_dag_v1> dagrun:<DagRun prediction_dag_v1 @ 2024-12-27 03:43:43.143920+00:00: manual__2024-12-27T03:43:43.143920+00:00, state:running, queued_at: 2024-12-27 03:43:43.156547+00:00. externally triggered: True>
[2024-12-27T03:44:23.007+0000] {logging_mixin.py:190} INFO - Failure caused by Process returned non-zero exit status 1.
The number of columns in this dataset is different from the one used to fit this transformer (when using the fit() method).
[2024-12-27T03:44:23.008+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=prediction_dag_v1, task_id=predict_model, run_id=manual__2024-12-27T03:43:43.143920+00:00, execution_date=20241227T034343, start_date=20241227T034351, end_date=20241227T034423
[2024-12-27T03:44:23.032+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-27T03:44:23.033+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task predict_model (Process returned non-zero exit status 1.
The number of columns in this dataset is different from the one used to fit this transformer (when using the fit() method).; 223)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 870, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 588, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
The number of columns in this dataset is different from the one used to fit this transformer (when using the fit() method).
[2024-12-27T03:44:23.065+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-27T03:44:23.096+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-27T03:44:23.101+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
