[2025-01-01T17:27:36.741+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-01T17:27:36.763+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prediction_dag_v1.predict_model manual__2025-01-01T17:27:30.659701+00:00 [queued]>
[2025-01-01T17:27:36.775+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prediction_dag_v1.predict_model manual__2025-01-01T17:27:30.659701+00:00 [queued]>
[2025-01-01T17:27:36.776+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-01T17:27:36.797+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): predict_model> on 2025-01-01 17:27:30.659701+00:00
[2025-01-01T17:27:36.808+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=333) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-01T17:27:36.811+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'prediction_dag_v1', 'predict_model', 'manual__2025-01-01T17:27:30.659701+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/02_prediction/02_prediction_v1.py', '--cfg-path', '/tmp/tmprmrmqird']
[2025-01-01T17:27:36.813+0000] {standard_task_runner.py:72} INFO - Started process 335 to run task
[2025-01-01T17:27:36.814+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask predict_model
[2025-01-01T17:27:36.890+0000] {task_command.py:467} INFO - Running <TaskInstance: prediction_dag_v1.predict_model manual__2025-01-01T17:27:30.659701+00:00 [running]> on host cbeec914397d
[2025-01-01T17:27:37.269+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cm' AIRFLOW_CTX_DAG_ID='prediction_dag_v1' AIRFLOW_CTX_TASK_ID='predict_model' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T17:27:30.659701+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-01T17:27:30.659701+00:00'
[2025-01-01T17:27:37.270+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-01T17:27:37.271+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-01T17:27:37.272+0000] {logging_mixin.py:190} INFO - Current task name:predict_model state:running start_date:2025-01-01 17:27:36.764381+00:00
[2025-01-01T17:27:37.273+0000] {logging_mixin.py:190} INFO - Dag name:prediction_dag_v1 and current dag run status:running
[2025-01-01T17:27:37.274+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-01T17:27:37.275+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvjlhlnzcl --python=python
[2025-01-01T17:27:37.276+0000] {process_utils.py:190} INFO - Output:
[2025-01-01T17:27:38.189+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.7.final.0-64 in 230ms
[2025-01-01T17:27:38.190+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venvjlhlnzcl, clear=False, no_vcs_ignore=False, global=False)
[2025-01-01T17:27:38.192+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-01-01T17:27:38.193+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-01-01T17:27:38.194+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-01-01T17:27:38.215+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvjlhlnzcl/bin/pip install -r /tmp/venvjlhlnzcl/requirements.txt
[2025-01-01T17:27:38.216+0000] {process_utils.py:190} INFO - Output:
[2025-01-01T17:27:39.784+0000] {process_utils.py:194} INFO - Collecting feature-engine==1.8.2 (from -r /tmp/venvjlhlnzcl/requirements.txt (line 1))
[2025-01-01T17:27:39.786+0000] {process_utils.py:194} INFO -   Using cached feature_engine-1.8.2-py2.py3-none-any.whl.metadata (9.9 kB)
[2025-01-01T17:27:39.826+0000] {process_utils.py:194} INFO - Collecting joblib==1.3.2 (from -r /tmp/venvjlhlnzcl/requirements.txt (line 2))
[2025-01-01T17:27:39.827+0000] {process_utils.py:194} INFO -   Using cached joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
[2025-01-01T17:27:40.037+0000] {process_utils.py:194} INFO - Collecting numpy==1.26.4 (from -r /tmp/venvjlhlnzcl/requirements.txt (line 3))
[2025-01-01T17:27:40.038+0000] {process_utils.py:194} INFO -   Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
[2025-01-01T17:27:40.234+0000] {process_utils.py:194} INFO - Collecting pandas==2.2.3 (from -r /tmp/venvjlhlnzcl/requirements.txt (line 4))
[2025-01-01T17:27:40.235+0000] {process_utils.py:194} INFO -   Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
[2025-01-01T17:27:40.461+0000] {process_utils.py:194} INFO - Collecting pendulum (from -r /tmp/venvjlhlnzcl/requirements.txt (line 5))
[2025-01-01T17:27:40.562+0000] {process_utils.py:194} INFO -   Downloading pendulum-3.0.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.9 kB)
[2025-01-01T17:27:40.680+0000] {process_utils.py:194} INFO - Collecting scikit-learn==1.5.2 (from -r /tmp/venvjlhlnzcl/requirements.txt (line 6))
[2025-01-01T17:27:40.681+0000] {process_utils.py:194} INFO -   Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
[2025-01-01T17:27:40.821+0000] {process_utils.py:194} INFO - Collecting scipy>=1.4.1 (from feature-engine==1.8.2->-r /tmp/venvjlhlnzcl/requirements.txt (line 1))
[2025-01-01T17:27:40.823+0000] {process_utils.py:194} INFO -   Using cached scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
[2025-01-01T17:27:40.905+0000] {process_utils.py:194} INFO - Collecting statsmodels>=0.11.1 (from feature-engine==1.8.2->-r /tmp/venvjlhlnzcl/requirements.txt (line 1))
[2025-01-01T17:27:40.906+0000] {process_utils.py:194} INFO -   Using cached statsmodels-0.14.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.2 kB)
[2025-01-01T17:27:40.945+0000] {process_utils.py:194} INFO - Collecting python-dateutil>=2.8.2 (from pandas==2.2.3->-r /tmp/venvjlhlnzcl/requirements.txt (line 4))
[2025-01-01T17:27:40.947+0000] {process_utils.py:194} INFO -   Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
[2025-01-01T17:27:41.015+0000] {process_utils.py:194} INFO - Collecting pytz>=2020.1 (from pandas==2.2.3->-r /tmp/venvjlhlnzcl/requirements.txt (line 4))
[2025-01-01T17:27:41.016+0000] {process_utils.py:194} INFO -   Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
[2025-01-01T17:27:41.061+0000] {process_utils.py:194} INFO - Collecting tzdata>=2022.7 (from pandas==2.2.3->-r /tmp/venvjlhlnzcl/requirements.txt (line 4))
[2025-01-01T17:27:41.063+0000] {process_utils.py:194} INFO -   Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
[2025-01-01T17:27:41.100+0000] {process_utils.py:194} INFO - Collecting threadpoolctl>=3.1.0 (from scikit-learn==1.5.2->-r /tmp/venvjlhlnzcl/requirements.txt (line 6))
[2025-01-01T17:27:41.101+0000] {process_utils.py:194} INFO -   Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
[2025-01-01T17:27:41.338+0000] {process_utils.py:194} INFO - Collecting time-machine>=2.6.0 (from pendulum->-r /tmp/venvjlhlnzcl/requirements.txt (line 5))
[2025-01-01T17:27:41.441+0000] {process_utils.py:194} INFO -   Downloading time_machine-2.16.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (21 kB)
[2025-01-01T17:27:41.485+0000] {process_utils.py:194} INFO - Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas==2.2.3->-r /tmp/venvjlhlnzcl/requirements.txt (line 4))
[2025-01-01T17:27:41.487+0000] {process_utils.py:194} INFO -   Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
[2025-01-01T17:27:41.574+0000] {process_utils.py:194} INFO - Collecting patsy>=0.5.6 (from statsmodels>=0.11.1->feature-engine==1.8.2->-r /tmp/venvjlhlnzcl/requirements.txt (line 1))
[2025-01-01T17:27:41.619+0000] {process_utils.py:194} INFO -   Using cached patsy-1.0.1-py2.py3-none-any.whl.metadata (3.3 kB)
[2025-01-01T17:27:41.681+0000] {process_utils.py:194} INFO - Collecting packaging>=21.3 (from statsmodels>=0.11.1->feature-engine==1.8.2->-r /tmp/venvjlhlnzcl/requirements.txt (line 1))
[2025-01-01T17:27:41.682+0000] {process_utils.py:194} INFO -   Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
[2025-01-01T17:27:41.700+0000] {process_utils.py:194} INFO - Using cached feature_engine-1.8.2-py2.py3-none-any.whl (374 kB)
[2025-01-01T17:27:41.701+0000] {process_utils.py:194} INFO - Using cached joblib-1.3.2-py3-none-any.whl (302 kB)
[2025-01-01T17:27:41.703+0000] {process_utils.py:194} INFO - Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
[2025-01-01T17:27:41.731+0000] {process_utils.py:194} INFO - Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
[2025-01-01T17:27:41.748+0000] {process_utils.py:194} INFO - Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
[2025-01-01T17:27:41.792+0000] {process_utils.py:194} INFO - Downloading pendulum-3.0.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (384 kB)
[2025-01-01T17:27:41.865+0000] {process_utils.py:194} INFO - Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
[2025-01-01T17:27:41.869+0000] {process_utils.py:194} INFO - Using cached pytz-2024.2-py2.py3-none-any.whl (508 kB)
[2025-01-01T17:27:41.871+0000] {process_utils.py:194} INFO - Using cached scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (40.8 MB)
[2025-01-01T17:27:41.931+0000] {process_utils.py:194} INFO - Using cached statsmodels-0.14.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.7 MB)
[2025-01-01T17:27:41.944+0000] {process_utils.py:194} INFO - Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
[2025-01-01T17:27:42.046+0000] {process_utils.py:194} INFO - Downloading time_machine-2.16.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33 kB)
[2025-01-01T17:27:42.065+0000] {process_utils.py:194} INFO - Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)
[2025-01-01T17:27:42.069+0000] {process_utils.py:194} INFO - Using cached packaging-24.2-py3-none-any.whl (65 kB)
[2025-01-01T17:27:42.080+0000] {process_utils.py:194} INFO - Using cached patsy-1.0.1-py2.py3-none-any.whl (232 kB)
[2025-01-01T17:27:42.081+0000] {process_utils.py:194} INFO - Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
[2025-01-01T17:27:42.309+0000] {process_utils.py:194} INFO - Installing collected packages: pytz, tzdata, threadpoolctl, six, packaging, numpy, joblib, scipy, python-dateutil, patsy, time-machine, scikit-learn, pandas, statsmodels, pendulum, feature-engine
[2025-01-01T17:27:58.920+0000] {process_utils.py:194} INFO - Successfully installed feature-engine-1.8.2 joblib-1.3.2 numpy-1.26.4 packaging-24.2 pandas-2.2.3 patsy-1.0.1 pendulum-3.0.0 python-dateutil-2.9.0.post0 pytz-2024.2 scikit-learn-1.5.2 scipy-1.14.1 six-1.17.0 statsmodels-0.14.4 threadpoolctl-3.5.0 time-machine-2.16.0 tzdata-2024.2
[2025-01-01T17:27:59.580+0000] {python.py:513} INFO - Use 'pickle' as serializer.
[2025-01-01T17:27:59.657+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvjlhlnzcl/bin/python /tmp/venv-callyous2b6p/script.py /tmp/venv-callyous2b6p/script.in /tmp/venv-callyous2b6p/script.out /tmp/venv-callyous2b6p/string_args.txt /tmp/venv-callyous2b6p/termination.log
[2025-01-01T17:27:59.665+0000] {process_utils.py:190} INFO - Output:
[2025-01-01T17:28:01.343+0000] {process_utils.py:194} INFO - Traceback (most recent call last):
[2025-01-01T17:28:01.344+0000] {process_utils.py:194} INFO -   File "/tmp/venv-callyous2b6p/script.py", line 96, in <module>
[2025-01-01T17:28:01.345+0000] {process_utils.py:194} INFO -     res = task_predict_model(*arg_dict["args"], **arg_dict["kwargs"])
[2025-01-01T17:28:01.346+0000] {process_utils.py:194} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-01T17:28:01.346+0000] {process_utils.py:194} INFO -   File "/tmp/venv-callyous2b6p/script.py", line 30, in task_predict_model
[2025-01-01T17:28:01.347+0000] {process_utils.py:194} INFO -     Variable.set(key="error_val", value="")
[2025-01-01T17:28:01.348+0000] {process_utils.py:194} INFO -     ^^^^^^^^
[2025-01-01T17:28:01.349+0000] {process_utils.py:194} INFO - NameError: name 'Variable' is not defined. Did you mean: 'callable'?
[2025-01-01T17:28:01.984+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 870, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 588, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
name 'Variable' is not defined
[2025-01-01T17:28:01.994+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-01T17:28:01.995+0000] {logging_mixin.py:190} INFO - Task start:2025-01-01 17:27:36.764381+00:00 end:2025-01-01 17:28:01.993742+00:00 duration:25.229361
[2025-01-01T17:28:01.996+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonVirtualenvDecoratedOperator): predict_model> dag:<DAG: prediction_dag_v1> dagrun:<DagRun prediction_dag_v1 @ 2025-01-01 17:27:30.659701+00:00: manual__2025-01-01T17:27:30.659701+00:00, state:running, queued_at: 2025-01-01 17:27:30.680300+00:00. externally triggered: True>
[2025-01-01T17:28:01.997+0000] {logging_mixin.py:190} INFO - Failure caused by Process returned non-zero exit status 1.
name 'Variable' is not defined
[2025-01-01T17:28:01.997+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=prediction_dag_v1, task_id=predict_model, run_id=manual__2025-01-01T17:27:30.659701+00:00, execution_date=20250101T172730, start_date=20250101T172736, end_date=20250101T172801
[2025-01-01T17:28:02.030+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-01T17:28:02.031+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 7 for task predict_model (Process returned non-zero exit status 1.
name 'Variable' is not defined; 335)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 870, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 588, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
name 'Variable' is not defined
[2025-01-01T17:28:02.078+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-01T17:28:02.098+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-01T17:28:02.122+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
