[2025-01-01T17:24:04.784+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-01T17:24:04.811+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prediction_dag_v1.predict_model manual__2025-01-01T17:23:55.219044+00:00 [queued]>
[2025-01-01T17:24:04.823+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prediction_dag_v1.predict_model manual__2025-01-01T17:23:55.219044+00:00 [queued]>
[2025-01-01T17:24:04.825+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-01T17:24:04.846+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): predict_model> on 2025-01-01 17:23:55.219044+00:00
[2025-01-01T17:24:04.856+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=113) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-01T17:24:04.860+0000] {standard_task_runner.py:72} INFO - Started process 115 to run task
[2025-01-01T17:24:04.859+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'prediction_dag_v1', 'predict_model', 'manual__2025-01-01T17:23:55.219044+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/02_prediction/02_prediction_v1.py', '--cfg-path', '/tmp/tmp89so_z2i']
[2025-01-01T17:24:04.862+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask predict_model
[2025-01-01T17:24:04.937+0000] {task_command.py:467} INFO - Running <TaskInstance: prediction_dag_v1.predict_model manual__2025-01-01T17:23:55.219044+00:00 [running]> on host cbeec914397d
[2025-01-01T17:24:05.456+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cm' AIRFLOW_CTX_DAG_ID='prediction_dag_v1' AIRFLOW_CTX_TASK_ID='predict_model' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T17:23:55.219044+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-01T17:23:55.219044+00:00'
[2025-01-01T17:24:05.458+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-01T17:24:05.459+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-01T17:24:05.460+0000] {logging_mixin.py:190} INFO - Current task name:predict_model state:running start_date:2025-01-01 17:24:04.812661+00:00
[2025-01-01T17:24:05.461+0000] {logging_mixin.py:190} INFO - Dag name:prediction_dag_v1 and current dag run status:running
[2025-01-01T17:24:05.462+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-01T17:24:05.465+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venv6cry8tb8 --python=python
[2025-01-01T17:24:05.467+0000] {process_utils.py:190} INFO - Output:
[2025-01-01T17:24:06.703+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.7.final.0-64 in 580ms
[2025-01-01T17:24:06.704+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venv6cry8tb8, clear=False, no_vcs_ignore=False, global=False)
[2025-01-01T17:24:06.705+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-01-01T17:24:06.706+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-01-01T17:24:06.707+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-01-01T17:24:06.727+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venv6cry8tb8/bin/pip install -r /tmp/venv6cry8tb8/requirements.txt
[2025-01-01T17:24:06.729+0000] {process_utils.py:190} INFO - Output:
[2025-01-01T17:24:08.502+0000] {process_utils.py:194} INFO - Collecting feature-engine==1.8.2 (from -r /tmp/venv6cry8tb8/requirements.txt (line 1))
[2025-01-01T17:24:08.689+0000] {process_utils.py:194} INFO -   Downloading feature_engine-1.8.2-py2.py3-none-any.whl.metadata (9.9 kB)
[2025-01-01T17:24:08.740+0000] {process_utils.py:194} INFO - Collecting joblib==1.3.2 (from -r /tmp/venv6cry8tb8/requirements.txt (line 2))
[2025-01-01T17:24:08.750+0000] {process_utils.py:194} INFO -   Downloading joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
[2025-01-01T17:24:08.996+0000] {process_utils.py:194} INFO - Collecting numpy==1.26.4 (from -r /tmp/venv6cry8tb8/requirements.txt (line 3))
[2025-01-01T17:24:09.007+0000] {process_utils.py:194} INFO -   Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
[2025-01-01T17:24:09.269+0000] {process_utils.py:194} INFO - Collecting pandas==2.2.3 (from -r /tmp/venv6cry8tb8/requirements.txt (line 4))
[2025-01-01T17:24:09.277+0000] {process_utils.py:194} INFO -   Downloading pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
[2025-01-01T17:24:09.468+0000] {process_utils.py:194} INFO - Collecting scikit-learn==1.5.2 (from -r /tmp/venv6cry8tb8/requirements.txt (line 5))
[2025-01-01T17:24:09.479+0000] {process_utils.py:194} INFO -   Downloading scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
[2025-01-01T17:24:09.782+0000] {process_utils.py:194} INFO - Collecting scipy>=1.4.1 (from feature-engine==1.8.2->-r /tmp/venv6cry8tb8/requirements.txt (line 1))
[2025-01-01T17:24:09.791+0000] {process_utils.py:194} INFO -   Downloading scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
[2025-01-01T17:24:10.082+0000] {process_utils.py:194} INFO - Collecting statsmodels>=0.11.1 (from feature-engine==1.8.2->-r /tmp/venv6cry8tb8/requirements.txt (line 1))
[2025-01-01T17:24:10.187+0000] {process_utils.py:194} INFO -   Downloading statsmodels-0.14.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.2 kB)
[2025-01-01T17:24:10.257+0000] {process_utils.py:194} INFO - Collecting python-dateutil>=2.8.2 (from pandas==2.2.3->-r /tmp/venv6cry8tb8/requirements.txt (line 4))
[2025-01-01T17:24:10.272+0000] {process_utils.py:194} INFO -   Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
[2025-01-01T17:24:10.449+0000] {process_utils.py:194} INFO - Collecting pytz>=2020.1 (from pandas==2.2.3->-r /tmp/venv6cry8tb8/requirements.txt (line 4))
[2025-01-01T17:24:10.466+0000] {process_utils.py:194} INFO -   Downloading pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
[2025-01-01T17:24:10.557+0000] {process_utils.py:194} INFO - Collecting tzdata>=2022.7 (from pandas==2.2.3->-r /tmp/venv6cry8tb8/requirements.txt (line 4))
[2025-01-01T17:24:10.584+0000] {process_utils.py:194} INFO -   Downloading tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
[2025-01-01T17:24:10.644+0000] {process_utils.py:194} INFO - Collecting threadpoolctl>=3.1.0 (from scikit-learn==1.5.2->-r /tmp/venv6cry8tb8/requirements.txt (line 5))
[2025-01-01T17:24:10.652+0000] {process_utils.py:194} INFO -   Downloading threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
[2025-01-01T17:24:10.690+0000] {process_utils.py:194} INFO - Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas==2.2.3->-r /tmp/venv6cry8tb8/requirements.txt (line 4))
[2025-01-01T17:24:10.700+0000] {process_utils.py:194} INFO -   Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
[2025-01-01T17:24:10.888+0000] {process_utils.py:194} INFO - Collecting patsy>=0.5.6 (from statsmodels>=0.11.1->feature-engine==1.8.2->-r /tmp/venv6cry8tb8/requirements.txt (line 1))
[2025-01-01T17:24:10.899+0000] {process_utils.py:194} INFO -   Downloading patsy-1.0.1-py2.py3-none-any.whl.metadata (3.3 kB)
[2025-01-01T17:24:10.954+0000] {process_utils.py:194} INFO - Collecting packaging>=21.3 (from statsmodels>=0.11.1->feature-engine==1.8.2->-r /tmp/venv6cry8tb8/requirements.txt (line 1))
[2025-01-01T17:24:10.965+0000] {process_utils.py:194} INFO -   Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
[2025-01-01T17:24:11.010+0000] {process_utils.py:194} INFO - Downloading feature_engine-1.8.2-py2.py3-none-any.whl (374 kB)
[2025-01-01T17:24:11.190+0000] {process_utils.py:194} INFO - Downloading joblib-1.3.2-py3-none-any.whl (302 kB)
[2025-01-01T17:24:11.247+0000] {process_utils.py:194} INFO - Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
[2025-01-01T17:24:15.694+0000] {process_utils.py:194} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 4.0 MB/s eta 0:00:00
[2025-01-01T17:24:15.703+0000] {process_utils.py:194} INFO - Downloading pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
[2025-01-01T17:24:18.574+0000] {process_utils.py:194} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 4.4 MB/s eta 0:00:00
[2025-01-01T17:24:18.583+0000] {process_utils.py:194} INFO - Downloading scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
[2025-01-01T17:24:20.760+0000] {process_utils.py:194} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 5.9 MB/s eta 0:00:00
[2025-01-01T17:24:20.771+0000] {process_utils.py:194} INFO - Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
[2025-01-01T17:24:20.827+0000] {process_utils.py:194} INFO - Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
[2025-01-01T17:24:20.909+0000] {process_utils.py:194} INFO - Downloading scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (40.8 MB)
[2025-01-01T17:24:30.061+0000] {process_utils.py:194} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 MB 4.5 MB/s eta 0:00:00
[2025-01-01T17:24:30.433+0000] {process_utils.py:194} INFO - Downloading statsmodels-0.14.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.7 MB)
[2025-01-01T17:24:33.269+0000] {process_utils.py:194} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 3.8 MB/s eta 0:00:00
[2025-01-01T17:24:33.284+0000] {process_utils.py:194} INFO - Downloading threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
[2025-01-01T17:24:33.305+0000] {process_utils.py:194} INFO - Downloading tzdata-2024.2-py2.py3-none-any.whl (346 kB)
[2025-01-01T17:24:33.404+0000] {process_utils.py:194} INFO - Downloading packaging-24.2-py3-none-any.whl (65 kB)
[2025-01-01T17:24:33.440+0000] {process_utils.py:194} INFO - Downloading patsy-1.0.1-py2.py3-none-any.whl (232 kB)
[2025-01-01T17:24:33.503+0000] {process_utils.py:194} INFO - Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
[2025-01-01T17:24:33.790+0000] {process_utils.py:194} INFO - Installing collected packages: pytz, tzdata, threadpoolctl, six, packaging, numpy, joblib, scipy, python-dateutil, patsy, scikit-learn, pandas, statsmodels, feature-engine
[2025-01-01T17:24:52.423+0000] {process_utils.py:194} INFO - Successfully installed feature-engine-1.8.2 joblib-1.3.2 numpy-1.26.4 packaging-24.2 pandas-2.2.3 patsy-1.0.1 python-dateutil-2.9.0.post0 pytz-2024.2 scikit-learn-1.5.2 scipy-1.14.1 six-1.17.0 statsmodels-0.14.4 threadpoolctl-3.5.0 tzdata-2024.2
[2025-01-01T17:24:52.806+0000] {python.py:513} INFO - Use 'pickle' as serializer.
[2025-01-01T17:24:52.834+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venv6cry8tb8/bin/python /tmp/venv-call3ix2ekrm/script.py /tmp/venv-call3ix2ekrm/script.in /tmp/venv-call3ix2ekrm/script.out /tmp/venv-call3ix2ekrm/string_args.txt /tmp/venv-call3ix2ekrm/termination.log
[2025-01-01T17:24:52.836+0000] {process_utils.py:190} INFO - Output:
[2025-01-01T17:24:54.269+0000] {process_utils.py:194} INFO - Traceback (most recent call last):
[2025-01-01T17:24:54.270+0000] {process_utils.py:194} INFO -   File "/tmp/venv-call3ix2ekrm/script.py", line 96, in <module>
[2025-01-01T17:24:54.271+0000] {process_utils.py:194} INFO -     res = task_predict_model(*arg_dict["args"], **arg_dict["kwargs"])
[2025-01-01T17:24:54.271+0000] {process_utils.py:194} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-01T17:24:54.272+0000] {process_utils.py:194} INFO -   File "/tmp/venv-call3ix2ekrm/script.py", line 28, in task_predict_model
[2025-01-01T17:24:54.272+0000] {process_utils.py:194} INFO -     import pendulum
[2025-01-01T17:24:54.273+0000] {process_utils.py:194} INFO -     ^^^^^^^^^^^^^^^
[2025-01-01T17:24:54.274+0000] {process_utils.py:194} INFO - ModuleNotFoundError: No module named 'pendulum'
[2025-01-01T17:24:54.881+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 870, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 588, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
No module named 'pendulum'
[2025-01-01T17:24:54.895+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-01T17:24:54.896+0000] {logging_mixin.py:190} INFO - Task start:2025-01-01 17:24:04.812661+00:00 end:2025-01-01 17:24:54.894726+00:00 duration:50.082065
[2025-01-01T17:24:54.897+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonVirtualenvDecoratedOperator): predict_model> dag:<DAG: prediction_dag_v1> dagrun:<DagRun prediction_dag_v1 @ 2025-01-01 17:23:55.219044+00:00: manual__2025-01-01T17:23:55.219044+00:00, state:running, queued_at: 2025-01-01 17:23:55.234249+00:00. externally triggered: True>
[2025-01-01T17:24:54.898+0000] {logging_mixin.py:190} INFO - Failure caused by Process returned non-zero exit status 1.
No module named 'pendulum'
[2025-01-01T17:24:54.899+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=prediction_dag_v1, task_id=predict_model, run_id=manual__2025-01-01T17:23:55.219044+00:00, execution_date=20250101T172355, start_date=20250101T172404, end_date=20250101T172454
[2025-01-01T17:24:54.926+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-01T17:24:54.928+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task predict_model (Process returned non-zero exit status 1.
No module named 'pendulum'; 115)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 870, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 588, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
No module named 'pendulum'
[2025-01-01T17:24:55.000+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-01T17:24:55.037+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-01T17:24:55.044+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
