[2025-01-01T23:20:00.501+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-01T23:20:00.535+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prediction_dag_v1.predict_model manual__2025-01-01T23:19:55.468296+00:00 [queued]>
[2025-01-01T23:20:00.553+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prediction_dag_v1.predict_model manual__2025-01-01T23:19:55.468296+00:00 [queued]>
[2025-01-01T23:20:00.556+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-01T23:20:00.578+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): predict_model> on 2025-01-01 23:19:55.468296+00:00
[2025-01-01T23:20:00.587+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3564) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-01T23:20:00.588+0000] {standard_task_runner.py:72} INFO - Started process 3573 to run task
[2025-01-01T23:20:00.589+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'prediction_dag_v1', 'predict_model', 'manual__2025-01-01T23:19:55.468296+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/02_prediction/02_prediction_v1.py', '--cfg-path', '/tmp/tmpmlbge4j2']
[2025-01-01T23:20:00.590+0000] {standard_task_runner.py:105} INFO - Job 79: Subtask predict_model
[2025-01-01T23:20:00.635+0000] {task_command.py:467} INFO - Running <TaskInstance: prediction_dag_v1.predict_model manual__2025-01-01T23:19:55.468296+00:00 [running]> on host 935cb972f608
[2025-01-01T23:20:01.159+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cm' AIRFLOW_CTX_DAG_ID='prediction_dag_v1' AIRFLOW_CTX_TASK_ID='predict_model' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T23:19:55.468296+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-01T23:19:55.468296+00:00'
[2025-01-01T23:20:01.161+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-01T23:20:01.162+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-01T23:20:01.162+0000] {logging_mixin.py:190} INFO - Current task name:predict_model state:running start_date:2025-01-01 23:20:00.536994+00:00
[2025-01-01T23:20:01.163+0000] {logging_mixin.py:190} INFO - Dag name:prediction_dag_v1 and current dag run status:running
[2025-01-01T23:20:01.164+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-01T23:20:01.166+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvroq96vce --system-site-packages --python=python
[2025-01-01T23:20:01.168+0000] {process_utils.py:190} INFO - Output:
[2025-01-01T23:20:01.980+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.7.final.0-64 in 242ms
[2025-01-01T23:20:01.981+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venvroq96vce, clear=False, no_vcs_ignore=False, global=True)
[2025-01-01T23:20:01.982+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-01-01T23:20:01.982+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-01-01T23:20:01.983+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-01-01T23:20:02.005+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvroq96vce/bin/pip install -r /tmp/venvroq96vce/requirements.txt
[2025-01-01T23:20:02.007+0000] {process_utils.py:190} INFO - Output:
[2025-01-01T23:20:03.859+0000] {process_utils.py:194} INFO - Collecting feature-engine==1.8.2 (from -r /tmp/venvroq96vce/requirements.txt (line 1))
[2025-01-01T23:20:03.861+0000] {process_utils.py:194} INFO -   Using cached feature_engine-1.8.2-py2.py3-none-any.whl.metadata (9.9 kB)
[2025-01-01T23:20:03.910+0000] {process_utils.py:194} INFO - Collecting joblib==1.3.2 (from -r /tmp/venvroq96vce/requirements.txt (line 2))
[2025-01-01T23:20:03.912+0000] {process_utils.py:194} INFO -   Using cached joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
[2025-01-01T23:20:03.914+0000] {process_utils.py:194} INFO - Requirement already satisfied: numpy==1.26.4 in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venvroq96vce/requirements.txt (line 3)) (1.26.4)
[2025-01-01T23:20:04.095+0000] {process_utils.py:194} INFO - Collecting pandas==2.2.3 (from -r /tmp/venvroq96vce/requirements.txt (line 4))
[2025-01-01T23:20:04.096+0000] {process_utils.py:194} INFO -   Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
[2025-01-01T23:20:04.134+0000] {process_utils.py:194} INFO - Requirement already satisfied: pendulum in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venvroq96vce/requirements.txt (line 5)) (3.0.0)
[2025-01-01T23:20:04.262+0000] {process_utils.py:194} INFO - Collecting scikit-learn==1.5.2 (from -r /tmp/venvroq96vce/requirements.txt (line 6))
[2025-01-01T23:20:04.264+0000] {process_utils.py:194} INFO -   Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
[2025-01-01T23:20:04.417+0000] {process_utils.py:194} INFO - Collecting scipy>=1.4.1 (from feature-engine==1.8.2->-r /tmp/venvroq96vce/requirements.txt (line 1))
[2025-01-01T23:20:04.419+0000] {process_utils.py:194} INFO -   Using cached scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
[2025-01-01T23:20:04.497+0000] {process_utils.py:194} INFO - Collecting statsmodels>=0.11.1 (from feature-engine==1.8.2->-r /tmp/venvroq96vce/requirements.txt (line 1))
[2025-01-01T23:20:04.500+0000] {process_utils.py:194} INFO -   Using cached statsmodels-0.14.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.2 kB)
[2025-01-01T23:20:04.511+0000] {process_utils.py:194} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.2.3->-r /tmp/venvroq96vce/requirements.txt (line 4)) (2.9.0.post0)
[2025-01-01T23:20:04.512+0000] {process_utils.py:194} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.2.3->-r /tmp/venvroq96vce/requirements.txt (line 4)) (2024.2)
[2025-01-01T23:20:04.513+0000] {process_utils.py:194} INFO - Requirement already satisfied: tzdata>=2022.7 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.2.3->-r /tmp/venvroq96vce/requirements.txt (line 4)) (2024.2)
[2025-01-01T23:20:04.558+0000] {process_utils.py:194} INFO - Collecting threadpoolctl>=3.1.0 (from scikit-learn==1.5.2->-r /tmp/venvroq96vce/requirements.txt (line 6))
[2025-01-01T23:20:04.563+0000] {process_utils.py:194} INFO -   Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
[2025-01-01T23:20:04.569+0000] {process_utils.py:194} INFO - Requirement already satisfied: time-machine>=2.6.0 in /home/***/.local/lib/python3.12/site-packages (from pendulum->-r /tmp/venvroq96vce/requirements.txt (line 5)) (2.16.0)
[2025-01-01T23:20:04.573+0000] {process_utils.py:194} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.2.3->-r /tmp/venvroq96vce/requirements.txt (line 4)) (1.16.0)
[2025-01-01T23:20:04.615+0000] {process_utils.py:194} INFO - Collecting patsy>=0.5.6 (from statsmodels>=0.11.1->feature-engine==1.8.2->-r /tmp/venvroq96vce/requirements.txt (line 1))
[2025-01-01T23:20:04.622+0000] {process_utils.py:194} INFO -   Using cached patsy-1.0.1-py2.py3-none-any.whl.metadata (3.3 kB)
[2025-01-01T23:20:04.627+0000] {process_utils.py:194} INFO - Requirement already satisfied: packaging>=21.3 in /home/***/.local/lib/python3.12/site-packages (from statsmodels>=0.11.1->feature-engine==1.8.2->-r /tmp/venvroq96vce/requirements.txt (line 1)) (24.1)
[2025-01-01T23:20:04.632+0000] {process_utils.py:194} INFO - Using cached feature_engine-1.8.2-py2.py3-none-any.whl (374 kB)
[2025-01-01T23:20:04.634+0000] {process_utils.py:194} INFO - Using cached joblib-1.3.2-py3-none-any.whl (302 kB)
[2025-01-01T23:20:04.636+0000] {process_utils.py:194} INFO - Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
[2025-01-01T23:20:04.651+0000] {process_utils.py:194} INFO - Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
[2025-01-01T23:20:04.669+0000] {process_utils.py:194} INFO - Using cached scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (40.8 MB)
[2025-01-01T23:20:04.730+0000] {process_utils.py:194} INFO - Using cached statsmodels-0.14.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.7 MB)
[2025-01-01T23:20:04.743+0000] {process_utils.py:194} INFO - Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
[2025-01-01T23:20:04.744+0000] {process_utils.py:194} INFO - Using cached patsy-1.0.1-py2.py3-none-any.whl (232 kB)
[2025-01-01T23:20:05.365+0000] {process_utils.py:194} INFO - Installing collected packages: threadpoolctl, scipy, patsy, joblib, scikit-learn, pandas, statsmodels, feature-engine
[2025-01-01T23:20:11.803+0000] {process_utils.py:194} INFO -   Attempting uninstall: pandas
[2025-01-01T23:20:11.810+0000] {process_utils.py:194} INFO -     Found existing installation: pandas 2.1.4
[2025-01-01T23:20:11.811+0000] {process_utils.py:194} INFO -     Not uninstalling pandas at /home/***/.local/lib/python3.12/site-packages, outside environment /tmp/venvroq96vce
[2025-01-01T23:20:11.812+0000] {process_utils.py:194} INFO -     Can't uninstall 'pandas'. No files were found to uninstall.
[2025-01-01T23:20:19.818+0000] {process_utils.py:194} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2025-01-01T23:20:19.819+0000] {process_utils.py:194} INFO - apache-***-providers-google 10.25.0 requires pandas<2.2,>=2.1.2; python_version >= "3.9", but you have pandas 2.2.3 which is incompatible.
[2025-01-01T23:20:19.820+0000] {process_utils.py:194} INFO - apache-***-providers-snowflake 5.8.0 requires pandas<2.2,>=2.1.2; python_version >= "3.9", but you have pandas 2.2.3 which is incompatible.
[2025-01-01T23:20:19.821+0000] {process_utils.py:194} INFO - Successfully installed feature-engine-1.8.2 joblib-1.3.2 pandas-2.2.3 patsy-1.0.1 scikit-learn-1.5.2 scipy-1.14.1 statsmodels-0.14.4 threadpoolctl-3.5.0
[2025-01-01T23:20:20.592+0000] {python.py:513} INFO - Use 'pickle' as serializer.
[2025-01-01T23:20:20.645+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvroq96vce/bin/python /tmp/venv-call2t60aae6/script.py /tmp/venv-call2t60aae6/script.in /tmp/venv-call2t60aae6/script.out /tmp/venv-call2t60aae6/string_args.txt /tmp/venv-call2t60aae6/termination.log
[2025-01-01T23:20:20.650+0000] {process_utils.py:190} INFO - Output:
[2025-01-01T23:20:22.459+0000] {process_utils.py:194} INFO - /home/***/.local/lib/python3.12/site-packages/***/configuration.py:859 FutureWarning: section/key [core/sql_alchemy_conn] has been deprecated, you should use[database/sql_alchemy_conn] instead. Please update your `conf.get*` call to use the new name
[2025-01-01T23:20:24.592+0000] {process_utils.py:194} INFO - 2025-01-01
[2025-01-01T23:20:25.323+0000] {python.py:240} INFO - Done. Returned value was: Sin predicción
[2025-01-01T23:20:25.344+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-01T23:20:25.345+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=prediction_dag_v1, task_id=predict_model, run_id=manual__2025-01-01T23:19:55.468296+00:00, execution_date=20250101T231955, start_date=20250101T232000, end_date=20250101T232025
[2025-01-01T23:20:25.355+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-01T23:20:25.356+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-01T23:20:25.357+0000] {logging_mixin.py:190} INFO - Dag name:prediction_dag_v1 queued_at:2025-01-01 23:19:55.493118+00:00
[2025-01-01T23:20:25.358+0000] {logging_mixin.py:190} INFO - Task hostname:935cb972f608 operator:_PythonVirtualenvDecoratedOperator
[2025-01-01T23:20:25.398+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-01T23:20:25.426+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-01T23:20:25.429+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
