[2025-01-01T17:40:43.023+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-01T17:40:43.049+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prediction_dag_v1.predict_model manual__2025-01-01T17:40:37.509939+00:00 [queued]>
[2025-01-01T17:40:43.059+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prediction_dag_v1.predict_model manual__2025-01-01T17:40:37.509939+00:00 [queued]>
[2025-01-01T17:40:43.060+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-01T17:40:43.073+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): predict_model> on 2025-01-01 17:40:37.509939+00:00
[2025-01-01T17:40:43.080+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=655) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-01T17:40:43.084+0000] {standard_task_runner.py:72} INFO - Started process 657 to run task
[2025-01-01T17:40:43.085+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'prediction_dag_v1', 'predict_model', 'manual__2025-01-01T17:40:37.509939+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/02_prediction/02_prediction_v1.py', '--cfg-path', '/tmp/tmppsczmtpb']
[2025-01-01T17:40:43.088+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask predict_model
[2025-01-01T17:40:43.143+0000] {task_command.py:467} INFO - Running <TaskInstance: prediction_dag_v1.predict_model manual__2025-01-01T17:40:37.509939+00:00 [running]> on host cbeec914397d
[2025-01-01T17:40:43.545+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cm' AIRFLOW_CTX_DAG_ID='prediction_dag_v1' AIRFLOW_CTX_TASK_ID='predict_model' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T17:40:37.509939+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-01T17:40:37.509939+00:00'
[2025-01-01T17:40:43.547+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-01T17:40:43.548+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-01T17:40:43.549+0000] {logging_mixin.py:190} INFO - Current task name:predict_model state:running start_date:2025-01-01 17:40:43.050272+00:00
[2025-01-01T17:40:43.549+0000] {logging_mixin.py:190} INFO - Dag name:prediction_dag_v1 and current dag run status:running
[2025-01-01T17:40:43.550+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-01T17:40:43.551+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvva7kqrrg --python=python
[2025-01-01T17:40:43.553+0000] {process_utils.py:190} INFO - Output:
[2025-01-01T17:40:44.312+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.7.final.0-64 in 204ms
[2025-01-01T17:40:44.313+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venvva7kqrrg, clear=False, no_vcs_ignore=False, global=False)
[2025-01-01T17:40:44.314+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-01-01T17:40:44.315+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-01-01T17:40:44.316+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-01-01T17:40:44.336+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvva7kqrrg/bin/pip install -r /tmp/venvva7kqrrg/requirements.txt
[2025-01-01T17:40:44.337+0000] {process_utils.py:190} INFO - Output:
[2025-01-01T17:40:45.900+0000] {process_utils.py:194} INFO - Collecting *** (from -r /tmp/venvva7kqrrg/requirements.txt (line 1))
[2025-01-01T17:40:46.118+0000] {process_utils.py:194} INFO -   Downloading ***-0.6.tar.gz (1.2 kB)
[2025-01-01T17:40:46.135+0000] {process_utils.py:194} INFO -   Installing build dependencies: started
[2025-01-01T17:40:48.581+0000] {process_utils.py:194} INFO -   Installing build dependencies: finished with status 'done'
[2025-01-01T17:40:48.582+0000] {process_utils.py:194} INFO -   Getting requirements to build wheel: started
[2025-01-01T17:40:49.211+0000] {process_utils.py:194} INFO -   Getting requirements to build wheel: finished with status 'error'
[2025-01-01T17:40:49.217+0000] {process_utils.py:194} INFO -   error: subprocess-exited-with-error
[2025-01-01T17:40:49.218+0000] {process_utils.py:194} INFO - 
[2025-01-01T17:40:49.219+0000] {process_utils.py:194} INFO -   × Getting requirements to build wheel did not run successfully.
[2025-01-01T17:40:49.220+0000] {process_utils.py:194} INFO -   │ exit code: 1
[2025-01-01T17:40:49.220+0000] {process_utils.py:194} INFO -   ╰─> [26 lines of output]
[2025-01-01T17:40:49.221+0000] {process_utils.py:194} INFO -       running egg_info
[2025-01-01T17:40:49.222+0000] {process_utils.py:194} INFO -       writing ***.egg-info/PKG-INFO
[2025-01-01T17:40:49.223+0000] {process_utils.py:194} INFO -       writing dependency_links to ***.egg-info/dependency_links.txt
[2025-01-01T17:40:49.223+0000] {process_utils.py:194} INFO -       writing top-level names to ***.egg-info/top_level.txt
[2025-01-01T17:40:49.224+0000] {process_utils.py:194} INFO -       reading manifest file '***.egg-info/SOURCES.txt'
[2025-01-01T17:40:49.225+0000] {process_utils.py:194} INFO -       writing manifest file '***.egg-info/SOURCES.txt'
[2025-01-01T17:40:49.226+0000] {process_utils.py:194} INFO -       Traceback (most recent call last):
[2025-01-01T17:40:49.226+0000] {process_utils.py:194} INFO -         File "/tmp/venvva7kqrrg/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
[2025-01-01T17:40:49.227+0000] {process_utils.py:194} INFO -           main()
[2025-01-01T17:40:49.227+0000] {process_utils.py:194} INFO -         File "/tmp/venvva7kqrrg/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
[2025-01-01T17:40:49.228+0000] {process_utils.py:194} INFO -           json_out['return_val'] = hook(**hook_input['kwargs'])
[2025-01-01T17:40:49.229+0000] {process_utils.py:194} INFO -                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-01T17:40:49.229+0000] {process_utils.py:194} INFO -         File "/tmp/venvva7kqrrg/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
[2025-01-01T17:40:49.230+0000] {process_utils.py:194} INFO -           return hook(config_settings)
[2025-01-01T17:40:49.230+0000] {process_utils.py:194} INFO -                  ^^^^^^^^^^^^^^^^^^^^^
[2025-01-01T17:40:49.231+0000] {process_utils.py:194} INFO -         File "/tmp/pip-build-env-eei_2dvu/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
[2025-01-01T17:40:49.231+0000] {process_utils.py:194} INFO -           return self._get_build_requires(config_settings, requirements=[])
[2025-01-01T17:40:49.232+0000] {process_utils.py:194} INFO -                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-01T17:40:49.233+0000] {process_utils.py:194} INFO -         File "/tmp/pip-build-env-eei_2dvu/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
[2025-01-01T17:40:49.233+0000] {process_utils.py:194} INFO -           self.run_setup()
[2025-01-01T17:40:49.233+0000] {process_utils.py:194} INFO -         File "/tmp/pip-build-env-eei_2dvu/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 522, in run_setup
[2025-01-01T17:40:49.234+0000] {process_utils.py:194} INFO -           super().run_setup(setup_script=setup_script)
[2025-01-01T17:40:49.234+0000] {process_utils.py:194} INFO -         File "/tmp/pip-build-env-eei_2dvu/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 320, in run_setup
[2025-01-01T17:40:49.235+0000] {process_utils.py:194} INFO -           exec(code, locals())
[2025-01-01T17:40:49.236+0000] {process_utils.py:194} INFO -         File "<string>", line 32, in <module>
[2025-01-01T17:40:49.236+0000] {process_utils.py:194} INFO -       RuntimeError: Please install package apache-*** instead of ***
[2025-01-01T17:40:49.237+0000] {process_utils.py:194} INFO -       [end of output]
[2025-01-01T17:40:49.237+0000] {process_utils.py:194} INFO - 
[2025-01-01T17:40:49.237+0000] {process_utils.py:194} INFO -   note: This error originates from a subprocess, and is likely not a problem with pip.
[2025-01-01T17:40:49.363+0000] {process_utils.py:194} INFO - error: subprocess-exited-with-error
[2025-01-01T17:40:49.364+0000] {process_utils.py:194} INFO - 
[2025-01-01T17:40:49.365+0000] {process_utils.py:194} INFO - × Getting requirements to build wheel did not run successfully.
[2025-01-01T17:40:49.365+0000] {process_utils.py:194} INFO - │ exit code: 1
[2025-01-01T17:40:49.366+0000] {process_utils.py:194} INFO - ╰─> See above for output.
[2025-01-01T17:40:49.367+0000] {process_utils.py:194} INFO - 
[2025-01-01T17:40:49.367+0000] {process_utils.py:194} INFO - note: This error originates from a subprocess, and is likely not a problem with pip.
[2025-01-01T17:40:49.473+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 868, in execute_callable
    self._prepare_venv(tmp_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 769, in _prepare_venv
    prepare_virtualenv(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/python_virtualenv.py", line 119, in prepare_virtualenv
    execute_in_subprocess(pip_cmd)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 175, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd, env=env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 198, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venvva7kqrrg/bin/pip', 'install', '-r', '/tmp/venvva7kqrrg/requirements.txt']' returned non-zero exit status 1.
[2025-01-01T17:40:49.487+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-01T17:40:49.488+0000] {logging_mixin.py:190} INFO - Task start:2025-01-01 17:40:43.050272+00:00 end:2025-01-01 17:40:49.487219+00:00 duration:6.436947
[2025-01-01T17:40:49.489+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonVirtualenvDecoratedOperator): predict_model> dag:<DAG: prediction_dag_v1> dagrun:<DagRun prediction_dag_v1 @ 2025-01-01 17:40:37.509939+00:00: manual__2025-01-01T17:40:37.509939+00:00, state:running, queued_at: 2025-01-01 17:40:37.533618+00:00. externally triggered: True>
[2025-01-01T17:40:49.490+0000] {logging_mixin.py:190} INFO - Failure caused by Command '['/tmp/venvva7kqrrg/bin/pip', 'install', '-r', '/tmp/venvva7kqrrg/requirements.txt']' returned non-zero exit status 1.
[2025-01-01T17:40:49.491+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=prediction_dag_v1, task_id=predict_model, run_id=manual__2025-01-01T17:40:37.509939+00:00, execution_date=20250101T174037, start_date=20250101T174043, end_date=20250101T174049
[2025-01-01T17:40:49.507+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-01T17:40:49.508+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 10 for task predict_model (Command '['/tmp/venvva7kqrrg/bin/pip', 'install', '-r', '/tmp/venvva7kqrrg/requirements.txt']' returned non-zero exit status 1.; 657)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 868, in execute_callable
    self._prepare_venv(tmp_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 769, in _prepare_venv
    prepare_virtualenv(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/python_virtualenv.py", line 119, in prepare_virtualenv
    execute_in_subprocess(pip_cmd)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 175, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd, env=env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 198, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venvva7kqrrg/bin/pip', 'install', '-r', '/tmp/venvva7kqrrg/requirements.txt']' returned non-zero exit status 1.
[2025-01-01T17:40:49.537+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-01T17:40:49.569+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-01T17:40:49.576+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
